name: publish project

on:
  release:
    types: [created]

#optional
# on:
#   push:
#     branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install Depedencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # optional
      # - name: Publish to PyPi
      #   env: 
      #     PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #     PYPI_TEST_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
      #   run: |
      #     make publish -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -e PYPI_TEST_PASSWORD=$PYPI_TEST_PASSWORD
